// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using PhiZone.Data;
//
//    var chartInfo = ChartInfo.FromJson(jsonString);

namespace Network.PhiZoneV1.Data
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    /// 章节列表
    ///
    /// 章节
    /// </summary>
    public partial class Chapter
    {
        /// <summary>
        /// 开放度，0：允许所有曲目投稿；1：允许经所有者审核后的曲目投稿；2：拒绝任何曲目投稿
        /// </summary>
        [JsonProperty("accessibility", Required = Required.Always)]
        public long Accessibility { get; set; }

        /// <summary>
        /// 评论数
        /// </summary>
        [JsonProperty("comment_count", Required = Required.Always)]
        public long CommentCount { get; set; }

        /// <summary>
        /// 简介
        /// </summary>
        [JsonProperty("description", Required = Required.AllowNull)]
        public string Description { get; set; }

        /// <summary>
        /// 包含该章节的活动
        /// </summary>
        [JsonProperty("events_incl", Required = Required.Always)]
        public string[] EventsIncl { get; set; }

        /// <summary>
        /// 章节 ID
        /// </summary>
        [JsonProperty("id", Required = Required.Always)]
        public long Id { get; set; }

        /// <summary>
        /// 绘画，图片文件（jpeg，png，webp），校验之后自动转换为 webp
        /// </summary>
        [JsonProperty("illustration", Required = Required.Always)]
        public string Illustration { get; set; }

        /// <summary>
        /// 画师
        /// </summary>
        [JsonProperty("illustrator", Required = Required.Always)]
        public string Illustrator { get; set; }

        /// <summary>
        /// 当前用户点赞情况，当前用户点赞资源，返回点赞 ID，否则为 null
        /// </summary>
        [JsonProperty("like", Required = Required.AllowNull)]
        public long? Like { get; set; }

        /// <summary>
        /// 赞数
        /// </summary>
        [JsonProperty("like_count", Required = Required.Always)]
        public long LikeCount { get; set; }

        /// <summary>
        /// 章节所有者
        /// </summary>
        [JsonProperty("owner", Required = Required.Always)]
        public Player Owner { get; set; }

        /// <summary>
        /// 包含曲目
        /// </summary>
        [JsonProperty("songs", Required = Required.Always)]
        public Songs Songs { get; set; }

        /// <summary>
        /// 副标题
        /// </summary>
        [JsonProperty("subtitle", Required = Required.Always)]
        public string Subtitle { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [JsonProperty("time", Required = Required.Always)]
        public string Time { get; set; }

        /// <summary>
        /// 标题
        /// </summary>
        [JsonProperty("title", Required = Required.Always)]
        public string Title { get; set; }
    }

    /// <summary>
    /// 曲目
    ///
    /// 包含曲目
    /// </summary>
    public partial class Song
    {
        /// <summary>
        /// 开放度，0：允许所有谱面投稿；1：允许经所有者审核后的谱面投稿；2：拒绝任何谱面投稿
        /// </summary>
        [JsonProperty("accessibility", Required = Required.Always)]
        public long Accessibility { get; set; }

        /// <summary>
        /// 参与活动情况，真：参与的活动未结束；假：参与的活动已结束或未参与活动
        /// </summary>
        [JsonProperty("at_event", Required = Required.Always)]
        public bool AtEvent { get; set; }

        /// <summary>
        /// 每分钟节拍数
        /// </summary>
        [JsonProperty("bpm", Required = Required.Always)]
        public string Bpm { get; set; }

        /// <summary>
        /// 包含该曲目的章节
        /// </summary>
        [JsonProperty("chapters", Required = Required.Always)]
        public Chapters Chapters { get; set; }

        /// <summary>
        /// 包含谱面
        /// </summary>
        [JsonProperty("charts", Required = Required.Always)]
        public Charts Charts { get; set; }

        /// <summary>
        /// 评论数
        /// </summary>
        [JsonProperty("comment_count", Required = Required.Always)]
        public long CommentCount { get; set; }

        /// <summary>
        /// 曲师，参与要求匿名的活动且活动未结束时为 null
        /// </summary>
        [JsonProperty("composer", Required = Required.AllowNull)]
        public string Composer { get; set; }

        /// <summary>
        /// 简介
        /// </summary>
        [JsonProperty("description", Required = Required.AllowNull)]
        public string Description { get; set; }

        /// <summary>
        /// 时长
        /// </summary>
        [JsonProperty("duration", Required = Required.Always)]
        public string Duration { get; set; }

        /// <summary>
        /// 版本，说明该曲目版本的出处（如原版，音游官方剪辑版，用户自剪版）
        /// </summary>
        [JsonProperty("edition", Required = Required.Always)]
        public string Edition { get; set; }

        /// <summary>
        /// 该曲目参加的活动
        /// </summary>
        [JsonProperty("event_part", Required = Required.AllowNull)]
        public long? EventPart { get; set; }

        /// <summary>
        /// 包含该曲目的活动
        /// </summary>
        [JsonProperty("events_incl", Required = Required.Always)]
        public string[] EventsIncl { get; set; }

        /// <summary>
        /// 曲目 ID
        /// </summary>
        [JsonProperty("id", Required = Required.Always)]
        public long Id { get; set; }

        /// <summary>
        /// 绘画，图片文件（jpeg，png，webp），校验之后自动转换为 webp
        /// </summary>
        [JsonProperty("illustration", Required = Required.Always)]
        public string Illustration { get; set; }

        /// <summary>
        /// 画师，参与要求匿名的活动且活动未结束时为 null
        /// </summary>
        [JsonProperty("illustrator", Required = Required.AllowNull)]
        public string Illustrator { get; set; }

        /// <summary>
        /// 谱面等级
        /// </summary>
        [JsonProperty("levels", Required = Required.Always)]
        public long[] Levels { get; set; }

        /// <summary>
        /// 当前用户点赞情况，当前用户点赞资源，返回点赞 ID，否则为 null
        /// </summary>
        [JsonProperty("like")]
        public long? Like { get; set; }

        /// <summary>
        /// 赞数
        /// </summary>
        [JsonProperty("like_count", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public long? LikeCount { get; set; }

        /// <summary>
        /// 歌词，以 lrc 为格式
        /// </summary>
        [JsonProperty("lyrics", Required = Required.AllowNull)]
        public string Lyrics { get; set; }

        /// <summary>
        /// 曲目名称
        /// </summary>
        [JsonProperty("name", Required = Required.Always)]
        public string Name { get; set; }

        /// <summary>
        /// 曲目开始距节奏的第一拍的时间间隔，以 ms 为单位
        /// </summary>
        [JsonProperty("offset", Required = Required.Always)]
        public long Offset { get; set; }

        /// <summary>
        /// 原创性，真：原创；假：转载
        /// </summary>
        [JsonProperty("original", Required = Required.Always)]
        public bool Original { get; set; }

        /// <summary>
        /// 预览结束时刻
        /// </summary>
        [JsonProperty("preview_end", Required = Required.Always)]
        public string PreviewEnd { get; set; }

        /// <summary>
        /// 预览开始时刻
        /// </summary>
        [JsonProperty("preview_start", Required = Required.Always)]
        public string PreviewStart { get; set; }

        /// <summary>
        /// 曲目文件，音频文件（mp3，ogg）
        /// </summary>
        [JsonProperty("song", Required = Required.Always)]
        public string SongSong { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [JsonProperty("time", Required = Required.Always)]
        public string Time { get; set; }

        /// <summary>
        /// 曲目上传者
        /// </summary>
        [JsonProperty("uploader", Required = Required.AllowNull)]
        public Owner Uploader { get; set; }
    }

    /// <summary>
    /// 评论
    /// </summary>
    public partial class 评论
    {
        [JsonProperty("chapter", Required = Required.AllowNull)]
        public long? Chapter { get; set; }

        [JsonProperty("chart", Required = Required.AllowNull)]
        public long? Chart { get; set; }

        [JsonProperty("content", Required = Required.Always)]
        public string Content { get; set; }

        [JsonProperty("creation", Required = Required.Always)]
        public string Creation { get; set; }

        [JsonProperty("deletion", Required = Required.AllowNull)]
        public string Deletion { get; set; }

        [JsonProperty("event", Required = Required.AllowNull)]
        public long? Event { get; set; }

        [JsonProperty("id", Required = Required.Always)]
        public long Id { get; set; }

        [JsonProperty("language", Required = Required.Always)]
        public string Language { get; set; }

        [JsonProperty("last_edit", Required = Required.Always)]
        public string LastEdit { get; set; }

        [JsonProperty("like", Required = Required.AllowNull)]
        public long? Like { get; set; }

        [JsonProperty("like_count", Required = Required.Always)]
        public long LikeCount { get; set; }

        [JsonProperty("pinned", Required = Required.Always)]
        public bool Pinned { get; set; }

        [JsonProperty("replies", Required = Required.Always)]
        public long Replies { get; set; }

        [JsonProperty("song", Required = Required.AllowNull)]
        public long? Song { get; set; }

        [JsonProperty("user", Required = Required.Always)]
        public Player User { get; set; }
    }

    /// <summary>
    /// 游玩记录
    /// </summary>
    public partial class Record
    {
        /// <summary>
        /// 准确率
        /// </summary>
        [JsonProperty("acc", Required = Required.Always)]
        public double Acc { get; set; }

        /// <summary>
        /// 游玩器 ID
        /// </summary>
        [JsonProperty("app", Required = Required.Always)]
        public long App { get; set; }

        /// <summary>
        /// Bad
        /// </summary>
        [JsonProperty("bad", Required = Required.Always)]
        public long Bad { get; set; }

        /// <summary>
        /// 谱面
        /// </summary>
        [JsonProperty("chart", Required = Required.Always)]
        public ChartInfo Chart { get; set; }

        /// <summary>
        /// 参与的活动
        /// </summary>
        [JsonProperty("event_part", Required = Required.AllowNull)]
        public System.Collections.Generic.Dictionary<string, object> EventPart { get; set; }

        /// <summary>
        /// 是否全连
        /// </summary>
        [JsonProperty("full_combo", Required = Required.Always)]
        public bool FullCombo { get; set; }

        /// <summary>
        /// Good (Early)
        /// </summary>
        [JsonProperty("good_early", Required = Required.Always)]
        public long GoodEarly { get; set; }

        /// <summary>
        /// Good 判定区间
        /// </summary>
        [JsonProperty("good_judgment", Required = Required.Always)]
        public long GoodJudgment { get; set; }

        /// <summary>
        /// Good (Late)
        /// </summary>
        [JsonProperty("good_late", Required = Required.Always)]
        public long GoodLate { get; set; }

        /// <summary>
        /// 游玩记录 ID
        /// </summary>
        [JsonProperty("id", Required = Required.Always)]
        public long Id { get; set; }

        /// <summary>
        /// 最高连击数
        /// </summary>
        [JsonProperty("max_combo", Required = Required.Always)]
        public long MaxCombo { get; set; }

        /// <summary>
        /// Miss
        /// </summary>
        [JsonProperty("miss", Required = Required.Always)]
        public long Miss { get; set; }

        /// <summary>
        /// Perfect
        /// </summary>
        [JsonProperty("perfect", Required = Required.Always)]
        public long Perfect { get; set; }

        /// <summary>
        /// Perfect 判定区间
        /// </summary>
        [JsonProperty("perfect_judgment", Required = Required.Always)]
        public long PerfectJudgment { get; set; }

        /// <summary>
        /// 玩家
        /// </summary>
        [JsonProperty("player", Required = Required.Always)]
        public Player Player { get; set; }

        /// <summary>
        /// RKS
        /// </summary>
        [JsonProperty("rks", Required = Required.Always)]
        public double Rks { get; set; }

        /// <summary>
        /// 分数
        /// </summary>
        [JsonProperty("score", Required = Required.Always)]
        public long Score { get; set; }

        /// <summary>
        /// 游玩时间
        /// </summary>
        [JsonProperty("time", Required = Required.Always)]
        public string Time { get; set; }
    }

    public partial class Extra
    {
        /// <summary>
        /// 最佳游玩记录
        /// </summary>
        [JsonProperty("best_records", Required = Required.Always)]
        public Record[] BestRecords { get; set; }

        /// <summary>
        /// 创作的谱面
        /// </summary>
        [JsonProperty("charts", Required = Required.Always)]
        public ChartInfo[] Charts { get; set; }

        /// <summary>
        /// 发表的评论
        /// </summary>
        [JsonProperty("comments", Required = Required.Always)]
        public 评论[] Comments { get; set; }

        /// <summary>
        /// 最近游玩记录
        /// </summary>
        [JsonProperty("recent_records", Required = Required.Always)]
        public Record[] RecentRecords { get; set; }

        /// <summary>
        /// 上传的曲目
        /// </summary>
        [JsonProperty("songs", Required = Required.Always)]
        public Song[] Songs { get; set; }
    }

    /// <summary>
    /// 用户
    ///
    /// 玩家
    /// </summary>
    public partial class User
    {
        /// <summary>
        /// 头像，图片文件（jpeg，png，gif，webp），校验之后自动转换为 webp
        /// </summary>
        [JsonProperty("avatar", Required = Required.Always)]
        public string Avatar { get; set; }

        /// <summary>
        /// 简介
        /// </summary>
        [JsonProperty("bio", Required = Required.AllowNull)]
        public string Bio { get; set; }

        /// <summary>
        /// 注册时间
        /// </summary>
        [JsonProperty("date_joined", Required = Required.Always)]
        public string DateJoined { get; set; }

        /// <summary>
        /// 生日
        /// </summary>
        [JsonProperty("date_of_birth", Required = Required.AllowNull)]
        public string DateOfBirth { get; set; }

        /// <summary>
        /// 经验
        /// </summary>
        [JsonProperty("exp", Required = Required.Always)]
        public long Exp { get; set; }

        /// <summary>
        /// 更多信息
        /// </summary>
        [JsonProperty("extra", Required = Required.AllowNull)]
        public Extra Extra { get; set; }

        /// <summary>
        /// 粉丝数
        /// </summary>
        [JsonProperty("fans", Required = Required.Always)]
        public long Fans { get; set; }

        /// <summary>
        /// 关注数
        /// </summary>
        [JsonProperty("following", Required = Required.Always)]
        public long Following { get; set; }

        /// <summary>
        /// 性别，0：未设置；1：男；2：女
        /// </summary>
        [JsonProperty("gender", Required = Required.Always)]
        public long Gender { get; set; }

        /// <summary>
        /// 用户 ID
        /// </summary>
        [JsonProperty("id", Required = Required.Always)]
        public long Id { get; set; }

        /// <summary>
        /// 激活状态，真：正常；假：被冻结
        /// </summary>
        [JsonProperty("is_active", Required = Required.Always)]
        public bool IsActive { get; set; }

        /// <summary>
        /// 是否关注
        /// </summary>
        [JsonProperty("is_following", Required = Required.AllowNull)]
        public bool? IsFollowing { get; set; }

        /// <summary>
        /// 语言，zh-Hans，en，jp
        /// </summary>
        [JsonProperty("language", Required = Required.Always)]
        public string Language { get; set; }

        /// <summary>
        /// 最后一次登录的时间
        /// </summary>
        [JsonProperty("last_login", Required = Required.AllowNull)]
        public string LastLogin { get; set; }

        /// <summary>
        /// 排名分
        /// </summary>
        [JsonProperty("rks", Required = Required.Always)]
        public double Rks { get; set; }

        /// <summary>
        /// 头衔
        /// </summary>
        [JsonProperty("tag", Required = Required.AllowNull)]
        public string Tag { get; set; }

        /// <summary>
        /// 用户类型，member，qualified，volunteer，admin，banned
        /// </summary>
        [JsonProperty("type", Required = Required.Always)]
        public string Type { get; set; }

        /// <summary>
        /// 用户名
        /// </summary>
        [JsonProperty("username", Required = Required.Always)]
        public string Username { get; set; }
    }

    /// <summary>
    /// 谱面
    ///
    /// 谱面列表
    /// </summary>
    public partial class ChartInfo
    {
        /// <summary>
        /// 参与活动情况，真：参与的活动未结束；假：参与的活动已结束或未参与活动
        /// </summary>
        [JsonProperty("at_event", Required = Required.Always)]
        public bool AtEvent { get; set; }

        /// <summary>
        /// 谱面文件，文本文件（json，pec）
        /// </summary>
        [JsonProperty("chart", Required = Required.AllowNull)]
        public string Chart { get; set; }

        /// <summary>
        /// 谱师，参与要求匿名的活动且活动未结束时为 null
        /// </summary>
        [JsonProperty("charter", Required = Required.AllowNull)]
        public string Charter { get; set; }

        /// <summary>
        /// 评论数
        /// </summary>
        [JsonProperty("comment_count", Required = Required.Always)]
        public long CommentCount { get; set; }

        /// <summary>
        /// 简介
        /// </summary>
        [JsonProperty("description", Required = Required.Always)]
        public string Description { get; set; }

        /// <summary>
        /// 定数
        /// </summary>
        [JsonProperty("difficulty", Required = Required.Always)]
        public double Difficulty { get; set; }

        /// <summary>
        /// 该谱面参加的活动
        /// </summary>
        [JsonProperty("event_part", Required = Required.AllowNull)]
        public long? EventPart { get; set; }

        /// <summary>
        /// 包含该谱面的活动
        /// </summary>
        [JsonProperty("events_incl", Required = Required.Always)]
        public string[] EventsIncl { get; set; }

        /// <summary>
        /// 格式，0：RPE JSON；1：PhiEditer Chart；2：Exported JSON
        /// </summary>
        [JsonProperty("format", Required = Required.Always)]
        public long Format { get; set; }

        /// <summary>
        /// 谱面 ID
        /// </summary>
        [JsonProperty("id", Required = Required.Always)]
        public long Id { get; set; }

        /// <summary>
        /// 等级，EZ，HD，IN，AT，SP，以及用户自定义的等级
        /// </summary>
        [JsonProperty("level", Required = Required.Always)]
        public string Level { get; set; }

        /// <summary>
        /// 等级类型，0：EZ；1：HD；2：IN；3：AT；4：SP
        /// </summary>
        [JsonProperty("level_type", Required = Required.Always)]
        public long LevelType { get; set; }

        /// <summary>
        /// 当前用户点赞情况，当前用户为资源点赞，返回点赞 ID，否则为 null
        /// </summary>
        [JsonProperty("like", Required = Required.AllowNull)]
        public long? Like { get; set; }

        /// <summary>
        /// 赞数
        /// </summary>
        [JsonProperty("like_count", Required = Required.Always)]
        public long LikeCount { get; set; }

        /// <summary>
        /// 音符数量
        /// </summary>
        [JsonProperty("notes", Required = Required.Always)]
        public long Notes { get; set; }

        /// <summary>
        /// 谱面所有者
        /// </summary>
        [JsonProperty("owner", Required = Required.AllowNull)]
        public Owner Owner { get; set; }

        /// <summary>
        /// 配置评价
        /// </summary>
        [JsonProperty("r_arrangement", Required = Required.Always)]
        public double RArrangement { get; set; }

        /// <summary>
        /// 契合度评价
        /// </summary>
        [JsonProperty("r_concord", Required = Required.Always)]
        public double RConcord { get; set; }

        /// <summary>
        /// 手感评价
        /// </summary>
        [JsonProperty("r_feel", Required = Required.Always)]
        public double RFeel { get; set; }

        /// <summary>
        /// 印象评价
        /// </summary>
        [JsonProperty("r_impression", Required = Required.Always)]
        public double RImpression { get; set; }

        /// <summary>
        /// 创新度评价
        /// </summary>
        [JsonProperty("r_innovativeness", Required = Required.Always)]
        public double RInnovativeness { get; set; }

        /// <summary>
        /// 视觉效果评价
        /// </summary>
        [JsonProperty("r_vfx", Required = Required.Always)]
        public double RVfx { get; set; }

        /// <summary>
        /// 是否为 ranked
        /// </summary>
        [JsonProperty("ranked", Required = Required.Always)]
        public bool Ranked { get; set; }

        /// <summary>
        /// 评价
        /// </summary>
        [JsonProperty("rating", Required = Required.Always)]
        public double Rating { get; set; }

        /// <summary>
        /// 游玩记录列表，如果 ranked，则为 RKS 前十；否则为最近十个记录
        /// </summary>
        [JsonProperty("records", Required = Required.AllowNull)]
        public Record[] Records { get; set; }

        /// <summary>
        /// 总评分
        /// </summary>
        [JsonProperty("score", Required = Required.Always)]
        public double Score { get; set; }

        /// <summary>
        /// 所属曲目
        /// </summary>
        [JsonProperty("song", Required = Required.Always)]
        public SongUnion Song { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [JsonProperty("time", Required = Required.Always)]
        public string Time { get; set; }

        /// <summary>
        /// 当前用户投票情况，当前用户为资源投票，返回投票，否则为 null
        /// </summary>
        [JsonProperty("vote", Required = Required.AllowNull)]
        public Vote Vote { get; set; }

        /// <summary>
        /// 实际票数
        /// </summary>
        [JsonProperty("votes", Required = Required.Always)]
        public long Votes { get; set; }
    }

    /// <summary>
    /// 投票
    /// </summary>
    public partial class Vote
    {
        /// <summary>
        /// 配置评分
        /// </summary>
        [JsonProperty("arrangement", Required = Required.Always)]
        public long Arrangement { get; set; }

        /// <summary>
        /// 谱面 ID
        /// </summary>
        [JsonProperty("chart", Required = Required.Always)]
        public long Chart { get; set; }

        /// <summary>
        /// 契合度评分
        /// </summary>
        [JsonProperty("concord", Required = Required.Always)]
        public long Concord { get; set; }

        /// <summary>
        /// 手感评分
        /// </summary>
        [JsonProperty("feel", Required = Required.Always)]
        public long Feel { get; set; }

        /// <summary>
        /// 投票 ID
        /// </summary>
        [JsonProperty("id", Required = Required.Always)]
        public long Id { get; set; }

        /// <summary>
        /// 印象评分
        /// </summary>
        [JsonProperty("impression", Required = Required.Always)]
        public long Impression { get; set; }

        /// <summary>
        /// 创新度评分
        /// </summary>
        [JsonProperty("innovativeness", Required = Required.Always)]
        public long Innovativeness { get; set; }

        /// <summary>
        /// 倍率
        /// </summary>
        [JsonProperty("multiplier", Required = Required.Always)]
        public long Multiplier { get; set; }

        /// <summary>
        /// 投票时间
        /// </summary>
        [JsonProperty("time", Required = Required.Always)]
        public string Time { get; set; }

        /// <summary>
        /// 投票总分
        /// </summary>
        [JsonProperty("total", Required = Required.Always)]
        public long Total { get; set; }

        /// <summary>
        /// 用户 ID
        /// </summary>
        [JsonProperty("user", Required = Required.Always)]
        public long User { get; set; }

        /// <summary>
        /// 视觉效果评分
        /// </summary>
        [JsonProperty("visual_effects", Required = Required.Always)]
        public long VisualEffects { get; set; }
    }

    /// <summary>
    /// 所属曲目
    /// </summary>
    public partial struct SongUnion
    {
        public long? Integer;
        public Song Song;

        public static implicit operator SongUnion(long Integer) => new SongUnion { Integer = Integer };
        public static implicit operator SongUnion(Song Song) => new SongUnion { Song = Song };
    }

    public partial struct Owner
    {
        public long? Integer;
        public User User;

        public static implicit operator Owner(long Integer) => new Owner { Integer = Integer };
        public static implicit operator Owner(User User) => new Owner { User = User };
        public bool IsNull => User == null && Integer == null;
    }

    /// <summary>
    /// 包含谱面
    /// </summary>
    public partial struct Charts
    {
        public ChartInfo[] ChartInfoArray;
        public long? Integer;

        public static implicit operator Charts(ChartInfo[] ChartInfoArray) => new Charts { ChartInfoArray = ChartInfoArray };
        public static implicit operator Charts(long Integer) => new Charts { Integer = Integer };
    }

    /// <summary>
    /// 包含该曲目的章节
    /// </summary>
    public partial struct Chapters
    {
        public Chapter[] ChapterArray;
        public long? Integer;

        public static implicit operator Chapters(Chapter[] ChapterArray) => new Chapters { ChapterArray = ChapterArray };
        public static implicit operator Chapters(long Integer) => new Chapters { Integer = Integer };
    }

    /// <summary>
    /// 包含曲目
    /// </summary>
    public partial struct Songs
    {
        public long? Integer;
        public Song[] SongArray;

        public static implicit operator Songs(long Integer) => new Songs { Integer = Integer };
        public static implicit operator Songs(Song[] SongArray) => new Songs { SongArray = SongArray };
    }

    public partial struct Player
    {
        public long? Integer;
        public User User;

        public static implicit operator Player(long Integer) => new Player { Integer = Integer };
        public static implicit operator Player(User User) => new Player { User = User };
    }

    public partial class ChartInfo
    {
        public static ChartInfo FromJson(string json) => JsonConvert.DeserializeObject<ChartInfo>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ChartInfo self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                OwnerConverter.Singleton,
                PlayerConverter.Singleton,
                ChaptersConverter.Singleton,
                SongsConverter.Singleton,
                ChartsConverter.Singleton,
                SongUnionConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class OwnerConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Owner) || t == typeof(Owner?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.Null:
                    return new Owner { };
                case JsonToken.Integer:
                    var integerValue = serializer.Deserialize<long>(reader);
                    return new Owner { Integer = integerValue };
                case JsonToken.StartObject:
                    var objectValue = serializer.Deserialize<User>(reader);
                    return new Owner { User = objectValue };
            }
            throw new Exception("Cannot unmarshal type Owner");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (Owner)untypedValue;
            if (value.IsNull)
            {
                serializer.Serialize(writer, null);
                return;
            }
            if (value.Integer != null)
            {
                serializer.Serialize(writer, value.Integer.Value);
                return;
            }
            if (value.User != null)
            {
                serializer.Serialize(writer, value.User);
                return;
            }
            throw new Exception("Cannot marshal type Owner");
        }

        public static readonly OwnerConverter Singleton = new OwnerConverter();
    }

    internal class PlayerConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Player) || t == typeof(Player?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.Integer:
                    var integerValue = serializer.Deserialize<long>(reader);
                    return new Player { Integer = integerValue };
                case JsonToken.StartObject:
                    var objectValue = serializer.Deserialize<User>(reader);
                    return new Player { User = objectValue };
            }
            throw new Exception("Cannot unmarshal type Player");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (Player)untypedValue;
            if (value.Integer != null)
            {
                serializer.Serialize(writer, value.Integer.Value);
                return;
            }
            if (value.User != null)
            {
                serializer.Serialize(writer, value.User);
                return;
            }
            throw new Exception("Cannot marshal type Player");
        }

        public static readonly PlayerConverter Singleton = new PlayerConverter();
    }

    internal class ChaptersConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Chapters) || t == typeof(Chapters?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.Integer:
                    var integerValue = serializer.Deserialize<long>(reader);
                    return new Chapters { Integer = integerValue };
                case JsonToken.StartArray:
                    var arrayValue = serializer.Deserialize<Chapter[]>(reader);
                    return new Chapters { ChapterArray = arrayValue };
            }
            throw new Exception("Cannot unmarshal type Chapters");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (Chapters)untypedValue;
            if (value.Integer != null)
            {
                serializer.Serialize(writer, value.Integer.Value);
                return;
            }
            if (value.ChapterArray != null)
            {
                serializer.Serialize(writer, value.ChapterArray);
                return;
            }
            throw new Exception("Cannot marshal type Chapters");
        }

        public static readonly ChaptersConverter Singleton = new ChaptersConverter();
    }

    internal class SongsConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Songs) || t == typeof(Songs?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.Integer:
                    var integerValue = serializer.Deserialize<long>(reader);
                    return new Songs { Integer = integerValue };
                case JsonToken.StartArray:
                    var arrayValue = serializer.Deserialize<Song[]>(reader);
                    return new Songs { SongArray = arrayValue };
            }
            throw new Exception("Cannot unmarshal type Songs");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (Songs)untypedValue;
            if (value.Integer != null)
            {
                serializer.Serialize(writer, value.Integer.Value);
                return;
            }
            if (value.SongArray != null)
            {
                serializer.Serialize(writer, value.SongArray);
                return;
            }
            throw new Exception("Cannot marshal type Songs");
        }

        public static readonly SongsConverter Singleton = new SongsConverter();
    }

    internal class ChartsConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Charts) || t == typeof(Charts?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.Integer:
                    var integerValue = serializer.Deserialize<long>(reader);
                    return new Charts { Integer = integerValue };
                case JsonToken.StartArray:
                    var arrayValue = serializer.Deserialize<ChartInfo[]>(reader);
                    return new Charts { ChartInfoArray = arrayValue };
            }
            throw new Exception("Cannot unmarshal type Charts");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (Charts)untypedValue;
            if (value.Integer != null)
            {
                serializer.Serialize(writer, value.Integer.Value);
                return;
            }
            if (value.ChartInfoArray != null)
            {
                serializer.Serialize(writer, value.ChartInfoArray);
                return;
            }
            throw new Exception("Cannot marshal type Charts");
        }

        public static readonly ChartsConverter Singleton = new ChartsConverter();
    }

    internal class SongUnionConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(SongUnion) || t == typeof(SongUnion?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.Integer:
                    var integerValue = serializer.Deserialize<long>(reader);
                    return new SongUnion { Integer = integerValue };
                case JsonToken.StartObject:
                    var objectValue = serializer.Deserialize<Song>(reader);
                    return new SongUnion { Song = objectValue };
            }
            throw new Exception("Cannot unmarshal type SongUnion");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (SongUnion)untypedValue;
            if (value.Integer != null)
            {
                serializer.Serialize(writer, value.Integer.Value);
                return;
            }
            if (value.Song != null)
            {
                serializer.Serialize(writer, value.Song);
                return;
            }
            throw new Exception("Cannot marshal type SongUnion");
        }

        public static readonly SongUnionConverter Singleton = new SongUnionConverter();
    }
}