// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Network.PhiZone.Data;
//
//    var userInfo = UserInfo.FromJson(jsonString);
using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Network.PhiZone.Data
{
    /// <summary>
    /// UserDetailedDtoResponseDto
    /// </summary>
    public partial class UserInfo
    {
        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public UserDetailedDto Data { get; set; }

        [JsonProperty("dateAvailable")]
        public DateTimeOffset? DateAvailable { get; set; }

        [JsonProperty("errors")]
        public ModelErrorDto[] Errors { get; set; }

        [JsonProperty("hasNext")]
        public bool? HasNext { get; set; }

        [JsonProperty("hasPrevious")]
        public bool? HasPrevious { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("perPage")]
        public long? PerPage { get; set; }

        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public long? Status { get; set; }

        [JsonProperty("total")]
        public long? Total { get; set; }
    }

    /// <summary>
    /// UserDetailedDto
    /// </summary>
    public partial class UserDetailedDto
    {
        [JsonProperty("avatar")]
        public string Avatar { get; set; }

        [JsonProperty("biography")]
        public string Biography { get; set; }

        [JsonProperty("dateFollowed")]
        public DateTimeOffset? DateFollowed { get; set; }

        [JsonProperty("dateJoined", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? DateJoined { get; set; }

        [JsonProperty("dateLastLoggedIn")]
        public DateTimeOffset? DateLastLoggedIn { get; set; }

        [JsonProperty("dateOfBirth")]
        public DateTimeOffset? DateOfBirth { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("emailConfirmed", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EmailConfirmed { get; set; }

        [JsonProperty("experience", NullValueHandling = NullValueHandling.Ignore)]
        public long? Experience { get; set; }

        [JsonProperty("followeeCount", NullValueHandling = NullValueHandling.Ignore)]
        public long? FolloweeCount { get; set; }

        [JsonProperty("followerCount", NullValueHandling = NullValueHandling.Ignore)]
        public long? FollowerCount { get; set; }

        [JsonProperty("gender", NullValueHandling = NullValueHandling.Ignore)]
        public long? Gender { get; set; }

        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public long? Id { get; set; }

        [JsonProperty("language")]
        public string Language { get; set; }

        [JsonProperty("notifications", NullValueHandling = NullValueHandling.Ignore)]
        public long? Notifications { get; set; }

        [JsonProperty("phoneNumber")]
        public string PhoneNumber { get; set; }

        [JsonProperty("phoneNumberConfirmed", NullValueHandling = NullValueHandling.Ignore)]
        public bool? PhoneNumberConfirmed { get; set; }

        [JsonProperty("region")]
        public string Region { get; set; }

        [JsonProperty("rks", NullValueHandling = NullValueHandling.Ignore)]
        public double? Rks { get; set; }

        [JsonProperty("role")]
        public string Role { get; set; }

        [JsonProperty("tag")]
        public string Tag { get; set; }

        [JsonProperty("twoFactorEnabled", NullValueHandling = NullValueHandling.Ignore)]
        public bool? TwoFactorEnabled { get; set; }

        [JsonProperty("userName")]
        public string UserName { get; set; }
    }

    /// <summary>
    /// ModelErrorDto
    /// </summary>
    public partial class ModelErrorDto
    {
        [JsonProperty("errors")]
        public string[] Errors { get; set; }

        [JsonProperty("field")]
        public string Field { get; set; }
    }

    // public partial class UserInfo
    // {
    //     public static UserInfo FromJson(string json) => JsonConvert.DeserializeObject<UserInfo>(json, Network.PhiZone.Data.Converter.Settings);
    // }
    //
    // public static class Serialize
    // {
    //     public static string ToJson(this UserInfo self) => JsonConvert.SerializeObject(self, Network.PhiZone.Data.Converter.Settings);
    // }
    //
    // internal static class Converter
    // {
    //     public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    //     {
    //         MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
    //         DateParseHandling = DateParseHandling.None,
    //         Converters =
    //         {
    //             new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
    //         },
    //     };
    // }
}